-- Active: 1659399879401@@35.226.146.116@3306@guimaraes-4211178-camila-leal
CREATE TABLE IF NOT EXISTS PRODUCTS_LIST (
    id INT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price FLOAT NOT NULL,
    qty_stock INT NOT NULL
    );

CREATE TABLE IF NOT EXISTS ORDERS_LIST(
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    clientName VARCHAR(50) NOT NULL,
    dueDate DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS ORDERS_PRODUCTS(
    productId INT NOT NULL,
    orderId VARCHAR(255) NOT NULL,
    productQuantity INT NOT NULL,
    FOREIGN KEY (productId) REFERENCES PRODUCTS_LIST(id),
    FOREIGN KEY (orderId) REFERENCES ORDERS_LIST(id)
    );

-- SELECT * FROM `ORDERS_LIST`;

-- SELECT * FROM `ORDERS_PRODUCTS`;

 SELECT * FROM `PRODUCTS_LIST`